import matplotlib.pyplot as plt
import csv

def load_csv(path):
    data = []
    with open(path, 'r') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            d = {}
            for k, v in row.items():
                try:
                    d[k] = int(v)
                except ValueError:
                    try:
                        d[k] = float(v)
                    except ValueError:
                        d[k] = v
            data.append(d)
    return data

def plot_smooth(x, y, label, color, window=50):
    smoothed = [sum(y[max(0, i-window+1):i+1]) / len(y[max(0, i-window+1):i+1]) for i in range(len(y))]
    plt.plot(x, y, color=color, alpha=0.2)
    plt.plot(x, smoothed, label=label, color=color, linewidth=1.5)

reinforce_small_data = load_csv('../logs/reinforce_small.csv')
reinforce_big_data = load_csv('../logs/reinforce_big.csv')
actorcritic_oldcourse_data = load_csv('../logs/actorcritic_logs_oldcourse.csv')
actorcritic_data = load_csv('../logs/actorcritic.csv')
actorcritic_batched_data = load_csv('../logs/actorcritic_batched.csv')
actorcritic_randomized_data = load_csv('../logs/actorcritic_randomized.csv')
actorcritic_2buoy = load_csv('../logs/actorcritic_2buoy.csv')

plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.title("Total Reward by Episode")
plot_smooth([d["episode"] for d in reinforce_big_data], [d["total_reward"] for d in reinforce_big_data], "Reinforce Big", 'orange')
plot_smooth([d["episode"] for d in reinforce_small_data], [d["total_reward"] for d in reinforce_small_data], "Reinforce Small", 'blue')
plt.xlabel("Episode")
plt.ylabel("Total Reward")
plt.legend()
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
plt.title("Ticks by Episode")
plot_smooth([d["episode"] for d in reinforce_big_data], [d["ticks"] for d in reinforce_big_data], "Reinforce Big", 'orange')
plot_smooth([d["episode"] for d in reinforce_small_data], [d["ticks"] for d in reinforce_small_data], "Reinforce Small", 'blue')
plt.xlabel("Episode")
plt.ylabel("Ticks")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("reinforce_comparison.png")

plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.title("Ticks by Episode")
plot_smooth([d["episode"] for d in reinforce_small_data], [d["ticks"] for d in reinforce_small_data], "Reinforce Small", 'blue')
plot_smooth([d["episode"] for d in actorcritic_oldcourse_data], [d["ticks"] for d in actorcritic_oldcourse_data], "Actor-Critic Old Course", 'green')
plt.xlabel("Episode")
plt.ylabel("Ticks")
plt.legend()
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
plt.title("Buoys Passed by Episode")
plot_smooth([d["episode"] for d in reinforce_small_data], [d["buoys_passed"] for d in reinforce_small_data], "Reinforce Small", 'blue')
plot_smooth([d["episode"] for d in actorcritic_oldcourse_data], [d["buoys_passed"] for d in actorcritic_oldcourse_data], "Actor-Critic Old Course", 'green')
plt.xlabel("Episode")
plt.ylabel("Buoys Passed")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("reinforce_vs_actorcritic_oldcourse.png")

plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.title("Total Reward by Episode")
plot_smooth([d["episode"] for d in actorcritic_data], [d["total_reward"] for d in actorcritic_data], "Actor-Critic", 'green')
plt.xlabel("Episode")
plt.ylabel("Total Reward")
plt.legend()
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
plt.title("Ticks by Episode")
plot_smooth([d["episode"] for d in actorcritic_data], [d["ticks"] for d in actorcritic_data], "Actor-Critic", 'green')
plt.xlabel("Episode")
plt.ylabel("Ticks")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("actorcritic_comparison.png")

plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.title("Total Reward by Episode")
plot_smooth([d["episode"] for d in actorcritic_batched_data], [d["total_reward"] for d in actorcritic_batched_data], "Actor-Critic", 'blue')
plt.xlabel("Episode")
plt.ylabel("Total Reward")
plt.legend()
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
plt.title("Ticks by Episode")
plot_smooth([d["episode"] for d in actorcritic_batched_data], [d["ticks"] for d in actorcritic_batched_data], "Actor-Critic", 'blue')
plt.xlabel("Episode")
plt.ylabel("Ticks")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("actorcritic_batched_comparison.png")

plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.title("Total Reward by Episode")
plot_smooth([d["episode"] for d in actorcritic_randomized_data], [d["total_reward"] for d in actorcritic_randomized_data], "Actor-Critic Randomized", 'green')
plot_smooth([d["episode"] for d in actorcritic_randomized_data], [d["std_total_reward"] for d in actorcritic_randomized_data], "Standardized Total Reward", 'orange')
plt.xlabel("Episode")
plt.ylabel("Total Reward")
plt.legend()
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
plt.title("Ticks by Episode")
plot_smooth([d["episode"] for d in actorcritic_randomized_data], [d["ticks"] for d in actorcritic_randomized_data], "Actor-Critic Randomized", 'green')
plot_smooth([d["episode"] for d in actorcritic_randomized_data], [d["std_ticks"] for d in actorcritic_randomized_data], "Standardized Ticks", 'orange')
plt.xlabel("Episode")
plt.ylabel("Ticks")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("actorcritic_randomized_comparison.png")

plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.title("Total Reward by Episode")
plot_smooth([d["episode"] for d in actorcritic_2buoy], [d["total_reward"] for d in actorcritic_2buoy], "Actor-Critic 2 Buoy", 'green')
plot_smooth([d["episode"] for d in actorcritic_2buoy], [d["std_total_reward"] for d in actorcritic_2buoy], "Standardized Total Reward", 'orange')
plt.xlabel("Episode")
plt.ylabel("Total Reward")
plt.legend()
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
plt.title("Ticks by Episode")
plot_smooth([d["episode"] for d in actorcritic_2buoy], [d["ticks"] for d in actorcritic_2buoy], "Actor-Critic 2 Buoy", 'green')
plot_smooth([d["episode"] for d in actorcritic_2buoy], [d["std_ticks"] for d in actorcritic_2buoy], "Standardized Ticks", 'orange')
plt.xlabel("Episode")
plt.ylabel("Ticks")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("actorcritic_2buoy_comparison.png")

plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.title("Standardized Total Reward by Episode")
plot_smooth([d["episode"] for d in actorcritic_data], [d["total_reward"] for d in actorcritic_data], "Actor-Critic", 'green')
plot_smooth([d["episode"] for d in actorcritic_batched_data], [d["total_reward"] for d in actorcritic_batched_data], "Actor-Critic Batched", 'blue')
plot_smooth([d["episode"] for d in actorcritic_randomized_data], [d["std_total_reward"] for d in actorcritic_randomized_data], "Actor-Critic Randomized", 'orange')
plt.xlabel("Episode")
plt.ylabel("Total Reward")
plt.legend()
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
plt.title("Standardized Ticks by Episode")
plot_smooth([d["episode"] for d in actorcritic_data], [d["ticks"] for d in actorcritic_data], "Actor-Critic", 'green')
plot_smooth([d["episode"] for d in actorcritic_batched_data], [d["ticks"] for d in actorcritic_batched_data], "Actor-Critic Batched", 'blue')
plot_smooth([d["episode"] for d in actorcritic_randomized_data], [d["std_ticks"] for d in actorcritic_randomized_data], "Actor-Critic Randomized", 'orange')
plt.xlabel("Episode")
plt.ylabel("Ticks")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("actorcritic_comparison_all.png")